package org.asd._Task_13_03;

public enum Skill {
    CIVIL_ENGINEER, ARCHITECT, SURVEYOR, ECONOMIST, TECHNOLOGIST,
    CRANE_OPERATOR, MASTER_OF_CONSTRUCTION_AND_INSTALLATION_WORKS,
    CARPENTER, ROOFER, PAINTER_PLASTERER,
}
